exclude: "config/exclude_accessions_mpxv.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors_hmpxv1.tsv"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config_hmpxv1.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"

strain_id_field: "accession"
display_strain_field: "strain_original"

build_name: "hmpxv1"
auspice_name: "monkeypox_hmpxv1"

## filter
min_date: 2022
min_length: 100000
sequences_per_group: "--sequences-per-group 30"
#subsample_max_sequences: "--subsample-max-sequences 500"
subsample_seed: "--subsample-seed 1234567" 
group_by: "--group-by year month country"
filters: "--exclude-where outbreak!=hMPXV-1 
                          lineage=A lineage=A.1 lineage=A.1.1 lineage=A.2 lineage=A.2.1 lineage=A.2.2 
                          accession=ON631963 accession=ON649879 accession=ON918611 accession=ON927248
                          country=Taiwan country=Sweden country=Brazil country=Mexico country=Japan country=Ireland
                          accession=ON918611 accession=ON927248 accession=OP204857 accession=ON983168 accession=OP605588
          --exclude-ambiguous-dates-by month"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true

## refine
timetree: true
root: "MK783032 MK783030"
clock_rate: 5.7e-5
clock_std_dev: 2e-5

## recency
recency: true

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/to_mask.bed"
  #mask_sites: "config/to_mask.txt"
